version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:mysql://localhost:3306/NeoShop
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Strong_Password123!

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: NeoShop
      MYSQL_USER: root
      MYSQL_PASSWORD: StrongPassword123!
      MYSQL_ROOT_PASSWORD: StrongPassword456!